# Generated by Django 2.2.5 on 2019-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
